name: test_minio_mirror
services:
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    command: server /data
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password"
    ports:
      - "9000:9000"
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      interval: 1s
      timeout: 10s
      retries: 5
  mc:
    image: minio/mc:RELEASE.2025-08-13T08-35-41Z-cpuv1
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - ./test_data:/mnt
    entrypoint: >
      /bin/sh -c "
      mc alias set minio http://minio:9000 admin password &&
      mc mb minio/data &&
      mc mirror /mnt/mybucket/foo minio/data/Food-11 &&
      mc ls minio/data/Food-11"
