name: ray_cluster
services:
  ray-head:
    image: rayproject/ray:2.54.0
    container_name: ray-head
    command: ray start --head --port=6379 --dashboard-host=0.0.0.0 --block
    ports:
      - "6379:6379" 
      - "8265:8265" 
    shm_size: '2g'
    user: root

  ray-worker-1:
    image: rayproject/ray:2.54.0
    container_name: ray-worker-1
    command: ["ray", "start", "--address=ray-head:6379", "--block"]
    shm_size: '2g'
    depends_on:
      - ray-head
